export const CREATE_SIGNIFICADO = 'CREATE_SIGNIFICADO';

export const GET_VISUAL_SHOW = 'GET_VISUAL_SHOW';
export const GET_UPLOADER_IMG = 'GET_UPLOADER_IMG';
export const GET_UPLOADER_VIDEO_SENA = 'GET_UPLOADER_VIDEO_SENA';
export const GET_UPLOADER_VIDEO_DESCRIP = 'GET_UPLOADER_VIDEO_DESCRIP';

export const SHOW_VISUAL_IMAGEN = 'SHOW_VISUAL_IMAGEN';
export const SHOW_VISUAL_VIDEO = 'SHOW_VISUAL_VIDEO';
export const SHOW_VISUAL_MASEJEMPLO = 'SHOW_VISUAL_MASEJEMPLO';

export const HIDE_VISUAL_IMAGEN = 'HIDE_VISUAL_IMAGEN';
export const HIDE_VISUAL_VIDEO = 'HIDE_VISUAL_VIDEO';
export const HIDE_VISUAL_MASEJEMPLO = 'HIDE_VISUAL_MASEJEMPLO';

export const ADD_UPLOADER_VIDEO_SENA = 'ADD_UPLOADER_VIDEO_SENA';
export const ADD_UPLOADER_VIDEO_DESCRIP = 'ADD_UPLOADER_VIDEO_DESCRIP';
export const ADD_IMAGENES_FILES = 'ADD_IMAGENES_FILES';

export const DELETE_IMAGENES_FILES = 'DELETE_IMAGENES_FILES';

export const SEARCH_SIGNIF = 'SEARCH_SIGNIF';
export const SEARCH_NOTESCORNELL = 'SEARCH_NOTESCORNELL';
